import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { BrowserRouter, Route, Routes } from "react-router-dom";
import DashboardPage from "./dashboard/page";
import OrganizationPage from "./organization/page";
import SignInPage from "./signin/page";
import HomePage from "./page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
